ALTER DATABASE - CHARACTER SET utf8 COLLATE utf8_unicode_ci;

DROP TABLE IF EXISTS rsvp
DROP TABLE IF EXISTS eventType
DROP TABLE IF EXISTS comment
DROP TABLE IF EXISTS event
DROP TABLE IF EXISTS profile


